# AppVeyor configuration file.
version: '1.7.2.{build}'

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\rom-properties

# Don't build if source files aren't modified.
only_commits:
  files:
    - appveyor.cmd
    - appveyor.yml
    - '**/CMakeLists.txt'
    - '**/*.cmd'
    - '**/*.sh'
    - extlib/**/*
    - src/**/*

environment:
  matrix:
    - platform: x86
      configuration: Debug
      compiler: msvc2015

    - platform: x86
      configuration: Release
      compiler: msvc2015

    - platform: x64
      configuration: Debug
      compiler: msvc2015

    - platform: x64
      configuration: Release
      compiler: msvc2015

    - platform: x86
      configuration: Debug
      compiler: mingw-w64

    - platform: x64
      configuration: Debug
      compiler: mingw-w64

# Run CMake with optional features turned off initially.
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor.cmd OFF

# Build once with optional features turned off,
# then build again with optional features turned on.
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cmake --build . --config %configuration%
  - cd ..
  - appveyor.cmd ON
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cmake --build . --config %configuration%

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - ctest -V -C %configuration%

after_test:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - ..\appveyor-artifacts.cmd
