# AppVeyor configuration file.
version: '1.2.0.{build}'

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\rom-properties

# Don't build if source files aren't modified.
only_commits:
  files:
    - appveyor.cmd
    - appveyor.yml
    - '**/CMakeLists.txt'
    - '**/*.cmd'
    - '**/*.sh'
    - extlib/**/*
    - src/**/*

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  NASM_URL: http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win64/nasm-2.12.02-installer-x64.exe

# Install NASM, then run CMake.
before_build:
  # TODO: Remove after https://github.com/appveyor/ci/issues/1426 is fixed
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -L -o nasminst.exe "%NASM_URL%"
  - start /wait nasminst /S
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor.cmd

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - msbuild ALL_BUILD.vcxproj

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ctest -V -C %CONFIGURATION%

# TODO: Automatic packaging?
